create table if not exists films (
    id          bigint generated by default as identity primary key not null,
    name        text not null,
    year        smallint not null,
    description text,
    rating      real not null
);

create index films_name on films using btree (name)