create table if not exists genres (
    id          smallint primary key,
    name        text not null
);

create table if not exists films_with_genres (
    genre_fk    smallint references genres (id),
    film_fk     bigint references films (id) on delete cascade,
    primary key (genre_fk, film_fk)
);

create index films_with_genres_genre_fk on films_with_genres using btree (genre_fk);

create table if not exists actors (
    id          bigint generated by default as identity primary key not null,
    first_name  text not null,
    second_name text not null
);

create index actors_second_name on actors using btree (second_name);

create table if not exists actors_roles (
    actor_fk    bigint references actors (id) on delete cascade,
    film_fk     bigint references films (id) on delete cascade,
    role        text not null,
    primary key (actor_fk, film_fk)
);

